
LOCAL_PATH := $(call my-dir)
P7ZIP_DIR := ../p7zip_15.09/CPP

include $(CLEAR_VARS)
LOCAL_MODULE := p7zip

LOCAL_CFLAGS := -DANDROID_NDK  -fexceptions \
	-DNDEBUG -D_REENTRANT -DENV_UNIX \
	-DBREAK_HANDLER \
	-DUNICODE -D_UNICODE -DUNIX_USE_WIN_FILE \
	-I$(LOCAL_PATH) \
	-I$(P7ZIP_DIR)/7zip/Archive \
	-I$(P7ZIP_DIR)/7zip/Archive/7z \
	-I$(P7ZIP_DIR)/7zip/Archive/BZip2 \
	-I$(P7ZIP_DIR)/7zip/Archive/Common \
	-I$(P7ZIP_DIR)/7zip/Archive/GZip \
	-I$(P7ZIP_DIR)/7zip/Archive/Cab \
	-I$(P7ZIP_DIR)/7zip/Archive/Lzma \
	-I$(P7ZIP_DIR)/7zip/Archive/Tar \
	-I$(P7ZIP_DIR)/7zip/Archive/Zip \
	-I$(P7ZIP_DIR)/7zip/Archive/Split \
	-I$(P7ZIP_DIR)/7zip/Archive/Z \
	-I$(P7ZIP_DIR)/7zip/Compress \
	-I$(P7ZIP_DIR)/7zip/Crypto \
	-I$(P7ZIP_DIR)/7zip/UI/Console \
	-I$(P7ZIP_DIR)/7zip/UI/Common \
	-I$(P7ZIP_DIR)/Windows \
	-I$(P7ZIP_DIR)/Common \
	-I$(P7ZIP_DIR)/7zip/Common \
	-I$(P7ZIP_DIR)/../C \
	-I$(P7ZIP_DIR)/myWindows \
	-I$(P7ZIP_DIR)/ \
	-I$(P7ZIP_DIR)/include_windows

LOCAL_SRC_FILES := \
  $(P7ZIP_DIR)/7zip/Archive/7z/7zCompressionMode.cpp \
  $(P7ZIP_DIR)/7zip/Archive/7z/7zDecode.cpp \
  $(P7ZIP_DIR)/7zip/Archive/7z/7zEncode.cpp \
  $(P7ZIP_DIR)/7zip/Archive/7z/7zExtract.cpp \
  $(P7ZIP_DIR)/7zip/Archive/7z/7zFolderInStream.cpp \
  $(P7ZIP_DIR)/7zip/Archive/7z/7zFolderOutStream.cpp \
  $(P7ZIP_DIR)/7zip/Archive/7z/7zHandler.cpp \
  $(P7ZIP_DIR)/7zip/Archive/7z/7zHandlerOut.cpp \
  $(P7ZIP_DIR)/7zip/Archive/7z/7zHeader.cpp \
  $(P7ZIP_DIR)/7zip/Archive/7z/7zIn.cpp \
  $(P7ZIP_DIR)/7zip/Archive/7z/7zOut.cpp \
  $(P7ZIP_DIR)/7zip/Archive/7z/7zProperties.cpp \
  $(P7ZIP_DIR)/7zip/Archive/7z/7zRegister.cpp \
  $(P7ZIP_DIR)/7zip/Archive/7z/7zSpecStream.cpp \
  $(P7ZIP_DIR)/7zip/Archive/7z/7zUpdate.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Bz2Handler.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Cab/CabBlockInStream.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Cab/CabHandler.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Cab/CabHeader.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Cab/CabIn.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Cab/CabRegister.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Common/CoderMixer2.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Common/CrossThreadProgress.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Common/DummyOutStream.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Common/FindSignature.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Common/HandlerOut.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Common/InStreamWithCRC.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Common/ItemNameUtils.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Common/MultiStream.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Common/OutStreamWithCRC.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Common/ParseProperties.cpp \
  $(P7ZIP_DIR)/7zip/Archive/DeflateProps.cpp \
  $(P7ZIP_DIR)/7zip/Archive/GzHandler.cpp \
  $(P7ZIP_DIR)/7zip/Archive/LzmaHandler.cpp \
  $(P7ZIP_DIR)/7zip/Archive/PpmdHandler.cpp \
  $(P7ZIP_DIR)/7zip/Archive/SplitHandler.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Tar/TarHandler.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Tar/TarHandlerOut.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Tar/TarHeader.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Tar/TarIn.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Tar/TarOut.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Tar/TarRegister.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Tar/TarUpdate.cpp \
  $(P7ZIP_DIR)/7zip/Archive/XzHandler.cpp \
  $(P7ZIP_DIR)/7zip/Archive/ZHandler.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Zip/ZipAddCommon.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Zip/ZipHandler.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Zip/ZipHandlerOut.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Zip/ZipIn.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Zip/ZipItem.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Zip/ZipOut.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Zip/ZipRegister.cpp \
  $(P7ZIP_DIR)/7zip/Archive/Zip/ZipUpdate.cpp \
  $(P7ZIP_DIR)/7zip/Common/CWrappers.cpp \
  $(P7ZIP_DIR)/7zip/Common/CreateCoder.cpp \
  $(P7ZIP_DIR)/7zip/Common/FilePathAutoRename.cpp \
  $(P7ZIP_DIR)/7zip/Common/FileStreams.cpp \
  $(P7ZIP_DIR)/7zip/Common/FilterCoder.cpp \
  $(P7ZIP_DIR)/7zip/Common/InBuffer.cpp \
  $(P7ZIP_DIR)/7zip/Common/InOutTempBuffer.cpp \
  $(P7ZIP_DIR)/7zip/Common/LimitedStreams.cpp \
  $(P7ZIP_DIR)/7zip/Common/MemBlocks.cpp \
  $(P7ZIP_DIR)/7zip/Common/MethodId.cpp \
  $(P7ZIP_DIR)/7zip/Common/MethodProps.cpp \
  $(P7ZIP_DIR)/7zip/Common/OffsetStream.cpp \
  $(P7ZIP_DIR)/7zip/Common/OutBuffer.cpp \
  $(P7ZIP_DIR)/7zip/Common/OutMemStream.cpp \
  $(P7ZIP_DIR)/7zip/Common/ProgressMt.cpp \
  $(P7ZIP_DIR)/7zip/Common/ProgressUtils.cpp \
  $(P7ZIP_DIR)/7zip/Common/PropId.cpp \
  $(P7ZIP_DIR)/7zip/Common/StreamBinder.cpp \
  $(P7ZIP_DIR)/7zip/Common/StreamObjects.cpp \
  $(P7ZIP_DIR)/7zip/Common/StreamUtils.cpp \
  $(P7ZIP_DIR)/7zip/Common/UniqBlocks.cpp \
  $(P7ZIP_DIR)/7zip/Common/VirtThread.cpp \
  $(P7ZIP_DIR)/7zip/Compress/BZip2Crc.cpp \
  $(P7ZIP_DIR)/7zip/Compress/BZip2Decoder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/BZip2Encoder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/BZip2Register.cpp \
  $(P7ZIP_DIR)/7zip/Compress/Bcj2Coder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/Bcj2Register.cpp \
  $(P7ZIP_DIR)/7zip/Compress/BcjCoder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/BcjRegister.cpp \
  $(P7ZIP_DIR)/7zip/Compress/BitlDecoder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/BranchMisc.cpp \
  $(P7ZIP_DIR)/7zip/Compress/BranchRegister.cpp \
  $(P7ZIP_DIR)/7zip/Compress/ByteSwap.cpp \
  $(P7ZIP_DIR)/7zip/Compress/CopyCoder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/CopyRegister.cpp \
  $(P7ZIP_DIR)/7zip/Compress/Deflate64Register.cpp \
  $(P7ZIP_DIR)/7zip/Compress/DeflateDecoder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/DeflateEncoder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/DeflateRegister.cpp \
  $(P7ZIP_DIR)/7zip/Compress/DeltaFilter.cpp \
  $(P7ZIP_DIR)/7zip/Compress/ImplodeDecoder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/ImplodeHuffmanDecoder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/LzOutWindow.cpp \
  $(P7ZIP_DIR)/7zip/Compress/Lzma2Decoder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/Lzma2Encoder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/Lzma2Register.cpp \
  $(P7ZIP_DIR)/7zip/Compress/LzmaDecoder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/LzmaEncoder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/LzmaRegister.cpp \
  $(P7ZIP_DIR)/7zip/Compress/LzxDecoder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/PpmdDecoder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/PpmdEncoder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/PpmdRegister.cpp \
  $(P7ZIP_DIR)/7zip/Compress/PpmdZip.cpp \
  $(P7ZIP_DIR)/7zip/Compress/QuantumDecoder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/ShrinkDecoder.cpp \
  $(P7ZIP_DIR)/7zip/Compress/ZDecoder.cpp \
  $(P7ZIP_DIR)/7zip/Crypto/7zAes.cpp \
  $(P7ZIP_DIR)/7zip/Crypto/7zAesRegister.cpp \
  $(P7ZIP_DIR)/7zip/Crypto/HmacSha1.cpp \
  $(P7ZIP_DIR)/7zip/Crypto/MyAes.cpp \
  $(P7ZIP_DIR)/7zip/Crypto/MyAesReg.cpp \
  $(P7ZIP_DIR)/7zip/Crypto/Pbkdf2HmacSha1.cpp \
  $(P7ZIP_DIR)/7zip/Crypto/RandGen.cpp \
  $(P7ZIP_DIR)/7zip/Crypto/WzAes.cpp \
  $(P7ZIP_DIR)/7zip/Crypto/ZipCrypto.cpp \
  $(P7ZIP_DIR)/7zip/Crypto/ZipStrong.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/ArchiveCommandLine.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/ArchiveExtractCallback.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/ArchiveOpenCallback.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/Bench.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/DefaultName.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/EnumDirItems.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/Extract.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/ExtractingFilePath.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/HashCalc.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/LoadCodecs.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/OpenArchive.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/PropIDUtils.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/SetProperties.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/SortUtils.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/TempFiles.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/Update.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/UpdateAction.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/UpdateCallback.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/UpdatePair.cpp \
  $(P7ZIP_DIR)/7zip/UI/Common/UpdateProduce.cpp \
  $(P7ZIP_DIR)/7zip/UI/Console/BenchCon.cpp \
  $(P7ZIP_DIR)/7zip/UI/Console/ConsoleClose.cpp \
  $(P7ZIP_DIR)/7zip/UI/Console/ExtractCallbackConsole.cpp \
  $(P7ZIP_DIR)/7zip/UI/Console/HashCon.cpp \
  $(P7ZIP_DIR)/7zip/UI/Console/List.cpp \
  $(P7ZIP_DIR)/7zip/UI/Console/Main.cpp \
  $(P7ZIP_DIR)/7zip/UI/Console/MainAr.cpp \
  $(P7ZIP_DIR)/7zip/UI/Console/OpenCallbackConsole.cpp \
  $(P7ZIP_DIR)/7zip/UI/Console/PercentPrinter.cpp \
  $(P7ZIP_DIR)/7zip/UI/Console/UpdateCallbackConsole.cpp \
  $(P7ZIP_DIR)/7zip/UI/Console/UserInputUtils.cpp \
  $(P7ZIP_DIR)/Common/CRC.cpp \
  $(P7ZIP_DIR)/Common/CommandLineParser.cpp \
  $(P7ZIP_DIR)/Common/CrcReg.cpp \
  $(P7ZIP_DIR)/Common/IntToString.cpp \
  $(P7ZIP_DIR)/Common/ListFileUtils.cpp \
  $(P7ZIP_DIR)/Common/MyString.cpp \
  $(P7ZIP_DIR)/Common/MyVector.cpp \
  $(P7ZIP_DIR)/Common/MyWindows.cpp \
  $(P7ZIP_DIR)/Common/Sha1Reg.cpp \
  $(P7ZIP_DIR)/Common/Sha256Reg.cpp \
  $(P7ZIP_DIR)/Common/StdInStream.cpp \
  $(P7ZIP_DIR)/Common/StdOutStream.cpp \
  $(P7ZIP_DIR)/Common/StringConvert.cpp \
  $(P7ZIP_DIR)/Common/StringToInt.cpp \
  $(P7ZIP_DIR)/Common/UTFConvert.cpp \
  $(P7ZIP_DIR)/Common/Wildcard.cpp \
  $(P7ZIP_DIR)/Common/XzCrc64Reg.cpp \
  $(P7ZIP_DIR)/Windows/ErrorMsg.cpp \
  $(P7ZIP_DIR)/Windows/FileDir.cpp \
  $(P7ZIP_DIR)/Windows/FileFind.cpp \
  $(P7ZIP_DIR)/Windows/FileIO.cpp \
  $(P7ZIP_DIR)/Windows/FileName.cpp \
  $(P7ZIP_DIR)/Windows/PropVariant.cpp \
  $(P7ZIP_DIR)/Windows/PropVariantConv.cpp \
  $(P7ZIP_DIR)/Windows/Synchronization.cpp \
  $(P7ZIP_DIR)/Windows/System.cpp \
  $(P7ZIP_DIR)/Windows/TimeUtils.cpp \
  $(P7ZIP_DIR)/myWindows/myAddExeFlag.cpp \
  $(P7ZIP_DIR)/myWindows/mySplitCommandLine.cpp \
  $(P7ZIP_DIR)/myWindows/wine_date_and_time.cpp \
  $(P7ZIP_DIR)/../C/7zCrc.c \
  $(P7ZIP_DIR)/../C/7zCrcOpt.c \
  $(P7ZIP_DIR)/../C/7zStream.c \
  $(P7ZIP_DIR)/../C/Aes.c \
  $(P7ZIP_DIR)/../C/Alloc.c \
  $(P7ZIP_DIR)/../C/Bcj2.c \
  $(P7ZIP_DIR)/../C/Bcj2Enc.c \
  $(P7ZIP_DIR)/../C/Bra.c \
  $(P7ZIP_DIR)/../C/Bra86.c \
  $(P7ZIP_DIR)/../C/BraIA64.c \
  $(P7ZIP_DIR)/../C/BwtSort.c \
  $(P7ZIP_DIR)/../C/CpuArch.c \
  $(P7ZIP_DIR)/../C/Delta.c \
  $(P7ZIP_DIR)/../C/HuffEnc.c \
  $(P7ZIP_DIR)/../C/LzFind.c \
  $(P7ZIP_DIR)/../C/LzFindMt.c \
  $(P7ZIP_DIR)/../C/Lzma2Dec.c \
  $(P7ZIP_DIR)/../C/Lzma2Enc.c \
  $(P7ZIP_DIR)/../C/LzmaDec.c \
  $(P7ZIP_DIR)/../C/LzmaEnc.c \
  $(P7ZIP_DIR)/../C/MtCoder.c \
  $(P7ZIP_DIR)/../C/Ppmd7.c \
  $(P7ZIP_DIR)/../C/Ppmd7Dec.c \
  $(P7ZIP_DIR)/../C/Ppmd7Enc.c \
  $(P7ZIP_DIR)/../C/Ppmd8.c \
  $(P7ZIP_DIR)/../C/Ppmd8Dec.c \
  $(P7ZIP_DIR)/../C/Ppmd8Enc.c \
  $(P7ZIP_DIR)/../C/Sha1.c \
  $(P7ZIP_DIR)/../C/Sha256.c \
  $(P7ZIP_DIR)/../C/Sort.c \
  $(P7ZIP_DIR)/../C/Threads.c \
  $(P7ZIP_DIR)/../C/Xz.c \
  $(P7ZIP_DIR)/../C/XzCrc64.c \
  $(P7ZIP_DIR)/../C/XzCrc64Opt.c \
  $(P7ZIP_DIR)/../C/XzDec.c \
  $(P7ZIP_DIR)/../C/XzEnc.c \
  $(P7ZIP_DIR)/../C/XzIn.c \
  JniWrapper.cpp \
  ZipUtils.cpp

include $(BUILD_SHARED_LIBRARY)

